# Basic Site Settings
locale                   : "en-US"
title                    : "Udbhav Dalavai"
title_separator          : "-"
name                     : &name "Udbhav Dalavai"
description              : &description "Incoming PhD student at Birkbeck, University of London"
url                      : https://udbhav.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Udbhav Dalavai"
  bio              : "Incoming PhD student at Birkbeck, University of London"
  location         : "London, UK"
  employer         : "Birkbeck, University of London"
  email            : "none@example.org"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "http://orcid.org/yourorcidurl"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"

  # Repositories and software development
  github           : "academicpages"

  # Social media
  bluesky          : "bsky.app"
  linkedin         : # Add your LinkedIn username here if desired
  twitter          : # Add your Twitter/X username here if desired
